language: ruby
rvm:
  - 2.2.3
before_script:
  - psql -c 'create database workshops_test;' -U workshops
services:
  - postgresql
addons:
  postgresql: '9.3'
test:
  adapter: postgresql
  database: travis_ci_test
  username: workshops
