language: ruby
rvm:
  - 2.2.3
before_script:
  - psql -c 'create database workshops_test;' -U postgres
before_script:
  - cp config/database.yml.travis config/database.yml
services:
  - postgresql
addons:
  postgresql: '9.3'
test:
  adapter: postgresql
  database: travis_ci_test
  username: postgres
